"""empty message

Revision ID: 918337e9fcc0
Revises: c105f75a3f73
Create Date: 2022-08-10 17:02:59.244804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918337e9fcc0'
down_revision = 'c105f75a3f73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'id')
    # ### end Alembic commands ###
