"""empty message

Revision ID: 9896d2c7657e
Revises: d8b4148a0e53
Create Date: 2022-08-10 12:53:55.272464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9896d2c7657e'
down_revision = 'd8b4148a0e53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('upcoming_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'upcoming_shows_count')
    # ### end Alembic commands ###
