"""empty message

Revision ID: c105f75a3f73
Revises: 9896d2c7657e
Create Date: 2022-08-10 13:24:04.393057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c105f75a3f73'
down_revision = '9896d2c7657e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'past_shows_count')
    # ### end Alembic commands ###
